# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ExactJointEntropy": "joint_entropy_computation.ipynb"}

modules = ["joint_entropy.py"]

doc_url = "https://blackhc.github.io/batchbald/"

git_url = "https://github.com/blackhc/batchbald/tree/master/"

def custom_doc_links(name): return None
